export enum NavEnum {
    PRODUCTION = 'PRODUCTION',
    COMPANY = 'COMPANY',
    NONE = 'NONE',
    RESPONSIVE = 'RESPONSIVE',
    RESPONSIVE_COMPANY = "RESPONSIVE_COMPANY",
    RESPONSIVE_PRODUCT = "RESPONSIVE_PRODUCT"
}
